// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcq0ABksx01-l_1_Np8FkeAQRleOu-hNw',
    appId: '1:73190196872:web:7579dc373ca7e067de013d',
    messagingSenderId: '73190196872',
    projectId: 'meditrack-2b228',
    authDomain: 'meditrack-2b228.firebaseapp.com',
    storageBucket: 'meditrack-2b228.appspot.com',
    measurementId: 'G-YG65J5H5QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5CldypSqwe3PeQalbUaz5vz6IYeOoGb0',
    appId: '1:73190196872:android:4664223fd9e5a2e8de013d',
    messagingSenderId: '73190196872',
    projectId: 'meditrack-2b228',
    storageBucket: 'meditrack-2b228.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8ai6bJA5gxqr0UV_k6mKX6kIVJ4QOck8',
    appId: '1:73190196872:ios:b2cfe3f81484d60dde013d',
    messagingSenderId: '73190196872',
    projectId: 'meditrack-2b228',
    storageBucket: 'meditrack-2b228.appspot.com',
    iosClientId: '73190196872-bsk0mnvv8lj22k2iarajvla7mdudbtd2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8ai6bJA5gxqr0UV_k6mKX6kIVJ4QOck8',
    appId: '1:73190196872:ios:b2cfe3f81484d60dde013d',
    messagingSenderId: '73190196872',
    projectId: 'meditrack-2b228',
    storageBucket: 'meditrack-2b228.appspot.com',
    iosClientId: '73190196872-bsk0mnvv8lj22k2iarajvla7mdudbtd2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcq0ABksx01-l_1_Np8FkeAQRleOu-hNw',
    appId: '1:73190196872:web:dad19229a19f6c92de013d',
    messagingSenderId: '73190196872',
    projectId: 'meditrack-2b228',
    authDomain: 'meditrack-2b228.firebaseapp.com',
    storageBucket: 'meditrack-2b228.appspot.com',
    measurementId: 'G-8HTPFZQRN6',
  );
}
